phpdoc:
  container_name: phpdoc
  image: phpdoc:latest
  environment:
    SYMFONY_DEBUG: "true"
    SYMFONY_ENV: "dev"
    SYMFONY__KERNEL__CACHE_DIR: "/tmp/cache"
    SYMFONY__KERNEL__LOGS_DIR: "/tmp/logs"
  volumes:
      - /opt/webapp
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/development:/etc/apache2/sites-available/development.override
  working_dir: "/opt/webapp"
  ports: [ "8000:80" ]
  links:
    - mysql

mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=phpdoc
      - MYSQL_USER=phpdoc
      - MYSQL_PASSWORD=phpdoc
      - MYSQL_ROOT_PASSWORD=phpdoc
