phpdoc:
  container_name: phpdoc
  build: .
  env_file: [".env"]
  environment:
    SYMFONY_DEBUG: "true"
    SYMFONY_ENV: "dev"
    SYMFONY__KERNEL__CACHE_DIR: "/tmp/cache"
    SYMFONY__KERNEL__LOGS_DIR: "/tmp/logs"
  volumes:
      - /opt/webapp
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/development:/etc/apache2/sites-available/development.override
  ports: [ "8000:80" ]
  links:
    - database

database:
    image: mysql
    ports:
      - "3306:3306"
    env_file: [".env"]
